# Generated by Django 3.2.13 on 2022-04-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0002_review_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='data',
        ),
    ]
