# Generated by Django 3.2.13 on 2022-04-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0003_remove_review_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='address',
        ),
        migrations.RemoveField(
            model_name='review',
            name='schoolname',
        ),
    ]
