# Generated by Django 3.2.13 on 2022-04-27 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0004_auto_20220427_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('addcollege_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recommendation.review')),
                ('collegereview_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recommendation.addcolleges')),
            ],
        ),
    ]
