# Generated by Django 3.2.13 on 2022-04-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0005_review_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='oldschool',
            field=models.CharField(blank=True, default=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='schoollocaton',
            field=models.CharField(blank=True, default=True, max_length=200, null=True),
        ),
    ]
