# Generated by Django 3.2.13 on 2022-04-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0008_auto_20220428_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(blank=True, default=True, max_length=200, null=True),
        ),
    ]
